[tool.poetry]
name = "petrotracker"
version = "0.1.0"
description = ""
authors = ["oliver2214 <dima.tovstokor@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
