# Generated by Django 4.2.7 on 2024-05-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_code', models.CharField(db_index=True, max_length=16)),
                ('shortname', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('currency', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=32)),
                ('shortname', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('site', models.CharField(blank=True, max_length=64)),
                ('CEO', models.CharField(blank=True, max_length=64)),
                ('ISIN', models.CharField(max_length=32)),
                ('exchange_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.exchanges')),
            ],
        ),
    ]
