# Generated by Django 4.2.7 on 2024-05-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchanges',
            name='exchange_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
