# Generated by Django 4.2.7 on 2024-05-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_exchanges_exchange_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickers',
            new_name='Securities',
        ),
    ]
