# Generated by Django 4.2.7 on 2024-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_tickers_securities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securities',
            name='ISIN',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
