# Generated by Django 4.2.7 on 2024-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_securities_isin'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='site',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
